# **Laboratorio 04 : Tuplas**

# Introducción
En Python se suelen llamar "estructura de datos" a cierta clase de tipos de datos más complejos, los cuales nos permiten organizar la información de manera más efectiva. En particular, nos permiten agrupar datos (cada uno de ellos con su tipo), e interactuar con ellos de la forma más apropiada. A continuación mostraremos las estructuras de datos más simple que gestiona Python, las TuUplas.

In [ ]:
# Definición de una tupla
mi_tupla = (1, 2, 3)

estudiantes_c12 = ("Castro", "Jean Carlos", "Renzo")

# Propiedades 
1.- Las Tuplas son **inmutables**, eso significa que una vez definido no se pueden modificar los valores asignados.

In [ ]:
#  index    0  1  2  3  4  5  6
mi_tupla = (10,20,30,40,50,60,70)

#mi_tupla[0] = 12  # Da error, propiedad INMUTABLE

2.- Se puede acceder a cualquier elemento de la Tupla usando indicae, empezando desde 0.

In [ ]:
#  index    0  1  2  3  4  5  6
mi_tupla = (10,20,30,40,50,60,70)


index = 2 # Accedo al elemento de la tercera posición
print(mi_tupla[2])

In [ ]:
mis_nombre = ("Jaime", "Gomez", "Marin")

# Imprimir , 1ro el apellido paterno, luego el nombre y apellido materno

print(mis_nombre[1])
print(mis_nombre[0])
print(mis_nombre[2])


3.- Las Tuplas se pueden desempaquetar, usando una nueva asignación

In [ ]:
#  index    0  1  2  3 
mi_tupla = (10,20,30,40)

(d1,d2,d3,d4) = mi_tupla

print(d4)

#print("El valor de la segunda posisión es  {}".format(d2))

# Funciones
Las Tuplas tiene funciones básicas que nos permiten realizar tareas concretas

## count()
Función que permite contar las ocurrencias en una Tupla

In [ ]:
estudiantes = ("Juan", "Maria", "Jose","Juan", "Juan")

# ¿Cálcular las veces que se repite el nombre "Juan" en la Tupla anterior

nro_veces = estudiantes.count("Juan")

print('Se repiten {} veces el nombre "Juan"'.format(nro_veces))

In [ ]:
numeros = (0,1,2,3,2,4,5,2,2)

nro_veces = numeros.count(2)

print('Se repiten {} veces el numero 2'.format(nro_veces))

In [ ]:
palabras = ("uno","uno","dos", "tres","uno")

## index()
Busca el valor en un tupla y te retorna el valor de la posición

In [ ]:
#                0        1       2      3       4
estudiantes = ("Juan", "Maria", "Jose","Juan", "Juan")

# ¿Cálcular la posición de "Maria" en la Tupla anterior

pos = estudiantes.index("Jose")

print(pos)

#print('El nombre de "Maria" se encuentra en el index = {}'.format(pos))

In [ ]:
numeros = (0,12,2,3,2,4,5,2,2)

# ¿Cálcular la posición del número 12 en la Tupla anterior

pos = numeros.index(12)

print('El número 12 se encuentra en el index = {}'.format(pos))

## len()
Retorna el tamaño de una Tupla

In [ ]:
estudiantes = ("Juan", "Maria", "ALberto","Maribel", "Inmaculada")

# ¿Cálcular cuantos estudiantes hay en la Tupla anterior?

nro_estudiantes = len(estudiantes)

print('El número  de estudiantes es = {}'.format(nro_estudiantes))

## min()

In [ ]:
mi_tupla_1 = (10,20,30,40)

minimo = min(mi_tupla_1)    
print(minimo)

## max()

In [ ]:
mi_tupla_1 = (10,20,30,40)

maximo = max(mi_tupla_1)    
print(maximo)

## sum()

In [ ]:
mi_tupla_1 = (10,20,30,40)

suma = sum(mi_tupla_1)    
print(suma)

# Slice

In [ ]:
#######################################
#              Slice
#
# [ start_index : stop_index : step ]
#######################################

#  index    0  1  2  3  4  5  6
mi_tupla = (10,20,30,40,50,60,70)

print("mi_tupla[1:4] =",mi_tupla[1:4])

print("mi_tupla[1:2:2] =",mi_tupla[1:2:2])
# (20,)
print("mi_tupla[1:6:2] =",mi_tupla[1:6:2])

# Operaciones
Las Tuplas pueden realizar las siguientes operaciones:
- Suma
- Multiplicación

## Suma

In [ ]:
 #  index      0  1  2  3
mi_tupla_1 = (10,20,30,40)
mi_tupla_2 = (100,200,300,400)

mi_tupla_f = mi_tupla_1 + mi_tupla_2
print(mi_tupla_f)

## Múltiplicación

In [ ]:
mi_tupla_1 = (10,20,30,40)
mi_tupla_tmp = mi_tupla_1 * 3
print(mi_tupla_tmp)

In [ ]:
mi_patron = ("-|-",)
print(type(mi_patron))
print(mi_patron)
mi_patron = mi_patron * 10
print(mi_patron)
print("".join(mi_patron))

# Tuplas con varios tipos de datos

In [ ]:
mi_tupla = ("JAIME","AAA","I","M","E",21,12.3,3)

pos = 0
print('mi_tupla[{}] = {}'.format(pos, mi_tupla[pos]))

pos = 6
print('mi_tupla[{}] = {}'.format(pos, mi_tupla[pos]))

pos = 7
print('mi_tupla[{}] = {}'.format(pos, mi_tupla[pos]))

# type()

Permita saber el tipo de datos de una variable

In [ ]:
mi_nro = 10
print(type(mi_nro)) 

mi_decimal = 10.4
print(type(mi_decimal)) 

es_martes = True
print(type(es_martes)) 

mi_nombre = "Jaime"
print(type(mi_nombre)) 

mi_tupla = ("JAIME","AAA","I","M","E",21,12.3,3)
print(type(mi_tupla))